version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /install_nginx.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /start_nginx.sh
      timeout: 300
      runas: root
