version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo No build steps for static site
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - index.html
    - appspec.yaml
    - scripts/install_nginx.sh
    - scripts/start_nginx.sh
  discard-paths: yes
